import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

import 'model/iconModel.dart';

TextStyle titleStyle = TextStyle(fontSize: 24, fontWeight: FontWeight.bold);

TextStyle contentStyle = TextStyle(fontFamily: 'SpoqaHanSansNeo');

TextStyle androidContentStyle = TextStyle(fontFamily: 'NotoSansKR');

List<IconModel> iconList = [
  IconModel('assets/daily/Chaos.png'),
  IconModel('assets/daily/Guardian.png'),
  IconModel('assets/daily/Epona.png'),
  IconModel('assets/week/WeeklyEpona.png'),
  IconModel('assets/week/AbyssDungeon.png'),
  IconModel('assets/expedition/ChallengeAbyss.png'),
  IconModel('assets/week/AbyssRaid.png'),
  IconModel('assets/week/Crops.png'),
  IconModel('assets/expedition/ChaosGate.png'),
  IconModel('assets/expedition/GhostShip.png'),
  IconModel('assets/expedition/Rehearsal.png'),
  IconModel('assets/expedition/Dejavu.png'),
  IconModel('assets/etc/GuildCoin.png'),
  IconModel('assets/etc/PirateCoin.png'),
  IconModel('assets/expedition/Dungeon.png'),
  IconModel('assets/etc/QuestNormal.png'),
  IconModel('assets/etc/SubjugationBattle.png'),
  IconModel('assets/expedition/ExpeditionFarm.png'),
  IconModel('assets/expedition/LifeEnergy.png'),
  IconModel('assets/expedition/LikeAbility.png'),
  IconModel('assets/expedition/PlatinumField.png'),
  IconModel('assets/etc/Cube.png'),
  IconModel('assets/etc/BossRush.png'),
  IconModel('assets/etc/Ticket.png'),
];

Map<String, Map<String, int>> merchantMapOfMap = {
  '아르테미스': {
    '로그힐': 1,
    '안게모스 산 기슭': 2,
    '국경지대': 3,
  },
  '유디아': {
    '살란드 구릉지': 4,
    '오즈혼 구릉지': 5,
  },
  '루테란 서부': {
    '자고라스 산': 6,
    '레이크바': 7,
    '메드리닉 수도원': 8,
    '빌브린 숲': 9,
    '격전의 평야': 10,
  },
  '루테란 동부': {
    '디오리카 평원': 11,
    '해무리 언덕': 12,
    '배꽃나무 자생지': 13,
    '흑장미 교회당': 14,
    '라니아 단구': 15,
    '보레아 영지': 16,
    '크로커니스 해변': 17,
  },
  '토토이크': {
    '바다향기 숲': 18,
    '달콤한 숲': 19,
    '성큼바위 숲': 20,
    '침묵하는 거인의 숲': 21,
  },
  '애니츠': {
    '델파이 현': 22,
    '등나무 언덕': 23,
    '소리의 숲': 24,
    '거울 계곡': 25,
    '황혼의 연무': 26,
  },
  '아르데타인': {
    '메마른 통로': 27,
    '갈라진 땅': 28,
    '네벨호른': 29,
    '바람결 구릉지': 30,
    '토트리치': 31,
    '리제 폭포': 32,
  },
  '베른 북부': {
    '크로나 항구': 33,
    '파르나 숲': 34,
    '페스나르 고원': 35,
    '베르닐 삼림': 36,
    '발란카르 산맥': 37,
  },
  '슈샤이어': {
    '얼어붙은 바다': 38,
    '칼날바람 언덕': 39,
    '서리감옥 고원' : 40,
    '머무른 시간의 호수': 41,
    '얼음나비 절벽': 42,
  },
  '로헨델': {
    '은빛물결 호수' : 43,
    '유리연꽃 호수' : 44,
    '바람향기 언덕' : 45,
    '파괴된 제나일' : 46,
    '엘조윈의 그늘' : 47,
  },
  '욘': {
    '시작의 땅' : 48,
    '미완의 정원' : 49,
    '검은모루 작업장' : 50,
    '무쇠망치 작업장' : 51,
    '기약의 땅' : 52,
  },
  '페이튼': {
    '칼라자 마을' : 53,
  },
  '파푸니카': {
    '얕은 바닷길' : 54,
    '별모래 해변' : 55,
    '티카티카 군락지' : 56,
    '비밀의 숲' : 57,
  },
  '베른 남부': {
    '칸다리아 영지' : 58,
    '벨리온 유적지' : 59,
  },
};
Map<String, int> merchantMap = {
  '로그힐': 1,
  '안게모스 산 기슭': 2,
  '국경지대': 3,
  '살란드 구릉지': 4,
  '오즈혼 구릉지': 5,
  '자고라스 산': 6,
  '레이크바': 7,
  '메드리닉 수도원': 8,
  '빌브린 숲': 9,
  '격전의 평야': 10,
  '디오리카 평원': 11,
  '해무리 언덕': 12,
  '배꽃나무 자생지': 13,
  '흑장미 교회당': 14,
  '라니아 단구': 15,
  '보레아 영지': 16,
  '크로커니스 해변': 17,
  '바다향기 숲': 18,
  '달콤한 숲': 19,
  '성큼바위 숲': 20,
  '침묵하는 거인의 숲': 21,
  '델파이 현': 22,
  '등나무 언덕': 23,
  '소리의 숲': 24,
  '거울 계곡': 25,
  '황혼의 연무': 26,
  '메마른 통로': 27,
  '갈라진 땅': 28,
  '네벨호른': 29,
  '바람결 구릉지': 30,
  '토트리치': 31,
  '리제 폭포': 32,
  '크로나 항구': 33,
  '파르나 숲': 34,
  '페스나르 고원': 35,
  '베르닐 삼림': 36,
  '발란카르 산맥': 37,
  '얼어붙은 바다': 38,
  '칼날바람 언덕': 39,
  '서리감옥 고원': 40,
  '머무른 시간의 호수': 41,
  '얼음나비 절벽': 42,
  '은빛물결 호수': 43,
  '유리연꽃 호수': 44,
  '바람향기 언덕': 45,
  '파괴된 제나일': 46,
  '엘조윈의 그늘': 47,
  '시작의 땅': 48,
  '미완의 정원': 49,
  '검은모루 작업장': 50,
  '무쇠망치 작업장': 51,
  '기약의 땅': 52,
  '칼라자 마을': 53,
  '얕은 바닷길': 54,
  '별모래 해변': 55,
  '티카티카 군락지': 56,
  '비밀의 숲': 57,
  '칸다리아 영지': 58,
  '벨리온 유적지': 59,
};

// 전 대륙 전 지역 백업본
// Continent('아르테미스', ['레온하트', '로그힐', '안게모스 산 기슭', '국경지대']),
// Continent('유디아', ['살란드 구릉지', '오즈혼 구릉지']),
// Continent('루테란 서부', ['자고라스 산', '레이크바', '메드리닉 수도원', '빌브린 숲', '격전의 평야']),
// Continent('루테란 동부', ['루테란 성', '디오리카 평원', '해무리 언덕', '배꽃나무 자생지', '흑장미 교회당', '라니아 단구', '보레아 영지', '갈기파도 항구', '크로커니스 해변']),
// Continent('토토이크', ['바다향기 숲', '모코코 마을', '달콤한 숲', '섬큼바위 숲', '침묵하는 거인의 숲']),
// Continent('애니츠', ['항구도시 창천', '델파이 현', '등나무 언덕', '소리의 숲', '거울 계곡', '황혼의 연무']),
// Continent('아르데타인', ['메마른 통로', '슈테른', '갈라진 땅', '네벨호른', '바람결 구릉지', '토트리치', '붉은 모래 사막', '리제 폭포']),
// Continent('베른 북부', ['크로나 항구', '베른 성', '라니아 마을', '파르나 숲', '페스나르 고원', '베르닐 삼림', '발란카르 산맥']),
// Continent('슈샤이어', ['얼어붙은 바다', '리겐스 마을', '칼날바람 언덕', '머무른 시간의 호수', '얼음나비 절벽']),
// Continent('로헨델', ['은빛물결 호수', '로아룬', '유리연꽃 호수', '바람향기 언덕', '파괴된 제나일', '엘조윈의 그늘']),
// Continent('욘', ['시작의 땅', '위대한 성', '미완의 정원', '검은모루 작업장', '무쇠망치 작업장', '기약의 땅']),
// Continent('페이튼', ['이름 없는 협곡', '칼라자 마을', '울부짖는 늪지대', '그늘진 절벽', '붉은 달의 흔적']),
// Continent('파푸니카', ['얕은 바닷길', '니아 마을', '별모래 해변', '티카티카 군락지', '비밀의 숲']),
// Continent('베른 남부', ['칸다리아 영지', '벨리온 유적지']),
